### PR TITLE
Add zd, fzf-gitlog, fzf-gitlog-multi, e

### PR DESCRIPTION
**Pull request by u1and0**
* zd <option> [path]: 'fuzzy-finder' + 'cd' = 'zd', The super function of _fd, _fda, _fdr, _fst, _cdf, _zz
* fzf-gitlog: git log browser
* fzf-gitlog-multi-widget: Multi-Selectable git show
* e <query>: Open 'frecency' files in $VISUAL editor

### CODE REVIEW

**Comment by atweiden** [comment]
@u1and0: could you alias fd to solve the naming conflict?

```sh
alias fd='/usr/bin/fd'
```

**Comment by u1and0** [comment]
I'm sorry for reply.
`alias fd` is nice idea.

**Comment by atweiden** [comment]
Just be sure to alias fd after you source fzf-extras. In your `~/.bashrc`:

```sh
source "$HOME/.fzf-extras/fzf-extras.sh"
alias fd='/usr/bin/fd'
```

If the state of [pr-11-feedback](https://github.com/atweiden/fzf-extras/tree/pr-11-feedback) looks acceptable to you, I'll squash the commits and merge.

**Comment by atweiden** [comment]
If you'd like to add your zplug instructions, you can add them to the [wiki](https://github.com/atweiden/fzf-extras/wiki).

**Comment by atweiden** [comment]
merged

**Pull request closed without merging**
